trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Notebooks'
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)'
    ArtifactName: 'Crypto Notebooks'
    publishLocation: Container
