trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - build-notebooks.yml
      - release-notebooks.yml

variables:
  vmImageName: ubuntu-latest

jobs:
  - job: Build
    pool:
      vmImage: $(vmImageName)
    steps:

      - script: |
          echo "Build artifact that contains all notebooks to be later consumed by release pipeline"
        displayName: "Compile notebooks"

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Notebooks'
        inputs:
          PathtoPublish: '$(Build.Repository.LocalPath)'
          ArtifactName: 'Crypto Notebooks'
          publishLocation: Container

      - script: |
          echo "Going into artifact staging directory"
          cd $(Build.ArtifactStagingDirectory)
          ls
          echo $(System.DefinitionId) > build_definition.txt
        displayName: Write Build Definition
