trigger:
  - none

resources:
  pipelines:
    - pipeline: crypto_analysis_build
      source: crypto_analysis_build
      trigger:
        branches:
          - main

variables:
    - name: vmImageName 
      value: ubuntu-latest
    - group: "DEV"
    - name: folderName
      value: release

jobs:
    - job: Release
      pool:
        vmImage: $(vmImageName)
      steps:

        - script: pip install databricks-cli
          displayName: Install Databricks CLI

        - script: |
            echo "
            $(databricksHost)
            $(databricksToken)
            " | databricks configure --token
          displayName: Configure Databricks CLI

        - script: |
            databricks workspace ls
          displayName: Test Databricks CLI

        - task: DownloadPipelineArtifact@2
          inputs: 
            buildType: "specific"
            project: "$(resources.pipeline.crypto_analysis_build.projectID)"
            pipeline: "$(resources.pipeline.crypto_analysis_build.pipelineID)"
            artifactName: Crypto Notebooks
            # definition: 5
            targetPath: $(System.DefaultWorkingDirectory)/databricks
        
        - script: ls $(System.DefaultWorkingDirectory)/databricks
          displayName: Check databricks folder contents

        - script: databricks repos list
          displayName: Check Repos in DB WS

        - script: databricks workspace list
          displayName: List databricks workspace objects

        - script: | 
            databricks workspace rm --recursive "/release"
            databricks workspace mkdirs "/release"
          displayName: Create Release in DB WS

          - script: |
              databricks import_dir $(System.DefaultWorkingDirectory)/databricks "/release/"
            displayName: Move Notebooks to DB WS