trigger:
  - none

resources:
  pipelines:
    - pipeline: crypto_analysis_release
      source: crypto_analysis_build
      trigger:
        branches:
          - main

variables:
    - name: vmImageName 
      value: ubuntu-latest
    - group: "DEV"
    - name: folderName
      value: release

jobs:
    - job: Release
      pool:
        vmImage: $(vmImageName)
      steps:
        - script: pip install databricks-cli
          displayName: Install Databricks CLI