trigger:
  - none

resources:
  pipelines:
    - pipeline: crypto_analysis_release
      source: crypto_analysis_build
      trigger:
        branches:
          - main

variables:
    - name: vmImageName 
      value: ubuntu-latest
    - group: "DEV"
    - name: folderName
      value: release

jobs:
    - job: Release
      pool:
        vmImage: $(vmImageName)
      steps:

        - script: pip install databricks-cli
          displayName: Install Databricks CLI

        - script: |
            echo "
            $(databricksHost)
            $(databricksToken)
            " | databricks configure --token
          displayName: Configure Databricks CLI

        - script: |
            databricks workspace ls
          displayName: Test Databricks CLI

        - task: DownloadPipelineArtifact@2
          inputs: 
            artifactName: Crypto Notebooks
            specificBuildWithTriggering: true
            targetPath: $(System.DefaultWorkingDirectory)/databricks
        
        - script: ls $(System.DefaultWorkingDirectory)/databricks